### ISSUE TITLE
Scroll indicator isn't updated when navigating with vim-mode

### ISSUE THREAD

**Issue by tonatiuh** [damassi/atom-scroll-percentage#4]
Steps to reproduce:
With the vim-mode package installed
Open a file and scroll it using the "j" or "k" keys
Then the scroll indicator isn't updated

On the other hand, if I scroll using the trackpad then the scroll indicator will update as expected.

**Comment by damassi** [comment]
Hi @tonatiuh, I too use the vim-mode. If I understand you correctly, what you're seeing is the threshold between each percentage point between 0 (top of the page) and 100 (bottom of the page) is not great enough to trigger a percentage update. As a way to visualize it, if there are 100 lines of code, and your viewport is exactly one line tall, then when you press j you'll see it advance to 1%, and again 2%, and so on, until you get to the bottom. The fact that there are different screen sizes and line heights makes it hard to see it advance sometimes, especially because you need to trigger the scroll before it begins calculating.

**Comment by damassi** [comment]
Going to close; feel free to reopen if i've missed something.
